#
# This code demonstrates the basic anova calculations for comparing the means between three
# sample groups.  As such, it yields an F score equivalent to that generated by aov().  The
# purpose of this demonstration is to acquaint the student with the underlying logic of anova.
# The data set comes from chapter 15 of The Analysis of Biological Data, and the algorithms
# are based on the formulas found there as well.  Students are encouraged to consult that
# chapter for a clear and concise presentation of anova.
#

setwd("c:/informatics/agstats/module_9")       # Set the working directory and read the data set.

circadian <- read.csv("circadian.csv", as.is = TRUE, header = TRUE)

control   <- subset(circadian, Treatment == "Control", select = "Data")
knees     <- subset(circadian, Treatment == "Knees", select = "Data")
eyes      <- subset(circadian, Treatment == "Eyes", select = "Data")

#
# Set properties for each group, including the underlying (grand) data set.
# Abbreviations are as follows: df = degrees of freedom, m = mean, sd = standard deviation,
#                                n = number of observations, num = numerator,
#                               ms = mean square (prefix).
#

grand.df   <- length(circadian$Data) - 3        
grand.m    <- mean(circadian$Data) 
grp.df     <- 2

control.m  <- mean(control$Data)               
knees.m    <- mean(knees$Data)
eyes.m     <- mean(eyes$Data)
                                               
control.sd <- sd(control$Data)                 
knees.sd   <- sd(knees$Data)
eyes.sd    <- sd(eyes$Data)
                                              
control.n  <- length(control$Data)            
knees.n    <- length(knees$Data)
eyes.n     <- length(eyes$Data)
                                               
control.df <- control.n - 1                   
knees.df   <- knees.n - 1
eyes.df    <- eyes.n - 1

                                      # Calcuate within groups variance.
num  <- (control.sd^2 * control.df) +          
        (knees.sd^2 * knees.df) + 
        (eyes.sd^2 * eyes.df)

ms_within  <- num / grand.df

                                      # Calculate between groups variance.
num  <- control.n * (control.m - grand.m)^2 +   
        knees.n * (knees.m - grand.m)^2 + 
        eyes.n * (eyes.m - grand.m)^2

ms_between <- num / grp.df                   
                                      
                                      # Calculate the final F score.
f_score    <- ms_between / ms_within           
